pygments: true
exclude: ["vendor"]
github: {
  "hostname": "github.com",
  "pages_hostname": "github.io",
  "project_title": "Fonts for Coding",
  "project_tagline": "A curated list of fonts for coding.",
  "owner_name": "john2x",
  "owner_url": "https://github.com/john2x",
  "repository_url": "https://github.com/john2x/fontsforcoding",
  "url": "http://john2x.github.io/fontsforcoding"
}
